import type { Article, ArticleSuggestion, MorningBrew, Profile } from "@/lib/types";

export const DEMO_USER_ID = "demo-user-00000000-0000-0000-0000-000000000001";

export const DEMO_PROFILE: Profile = {
  id: DEMO_USER_ID,
  email: "demo@genpact.com",
  full_name: "Demo Admin",
  avatar_url: null,
  role: "admin",
  created_at: new Date().toISOString(),
};

export const DEMO_ARTICLES: Article[] = [
  // ── Steve's YouTube picks ────────────────────────────────────────────────
  {
    id: "demo-art-vid-0000-0000-000000000001",
    title: "Boris Chen: Claude Code and the Future of Software Engineering",
    summary: "The inventor of Claude Code at Sequoia's AI Ascent — writes most of his code on his phone, shipped 150 PRs in a day, and believes coding is now essentially solved. Being close to the business problem is the new most valuable skill.",
    ai_summary: "Boris Chen, creator of Claude Code, makes the provocative case that software engineering as we know it is solved — and that proximity to the business problem is becoming the most valuable skill. His live demo of shipping 150 pull requests in a single day from his phone illustrates how AI agents collapse the gap between idea and production. A must-watch for anyone building with or alongside AI.",
    content: `Key takeaways from Boris's talk at AI Ascent:

• He writes most of his code on his phone
• Shipped 150 PRs in a single day — from his phone
• Believes coding is "solved" and being close to the business problem is going to matter more than coding skill
• Claude Code itself is surprisingly simple: TypeScript, React, no magic
• As models improve, you end up stripping out features, not adding them — simplicity wins`,
    url: "https://youtu.be/SlGRN8jh2RI",
    image_url: "https://img.youtube.com/vi/SlGRN8jh2RI/maxresdefault.jpg",
    category: "AI & Automation",
    tags: ["Claude Code", "Software Engineering", "AI Agents"],
    source: "Sequoia AI Ascent 2025",
    author: "Boris Chen · Anthropic",
    ai_tags: ["Developer Tools", "Future of Work", "Agentic AI"],
    is_featured: true,
    status: "published" as const,
    content_type: "video" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000001",
    title: "The AI-First Enterprise: How Leading Companies Are Restructuring for Generative AI",
    summary: "An in-depth look at how Fortune 500 companies are embedding AI into their core operating models.",
    ai_summary: "Leading enterprises are moving beyond AI pilots to full-scale transformation — restructuring teams, processes, and technology stacks around generative AI. The article examines the operating model shifts required to become truly AI-first and the cultural changes that must accompany them.",
    content: `The question is no longer whether to adopt generative AI, but how fast and how deeply to embed it into every layer of the enterprise.

The companies pulling ahead aren't running pilots — they're restructuring. They're reorganizing teams around AI capabilities, rewriting job descriptions, and building internal "AI factories" that continuously produce and deploy new models.

Three patterns emerge among the leaders: first, they appoint AI transformation officers with true P&L accountability. Second, they invest heavily in data infrastructure before deploying models. Third, they treat AI literacy as a core competency for every employee, not just technologists.

For operations-intensive businesses like Genpact's clients, the opportunity is particularly acute. Intelligent automation of transactional work can unlock 30-40% capacity — but only if leaders are willing to redesign processes end-to-end rather than layering AI on top of broken workflows.`,
    url: "https://hbr.org/ai-first-enterprise",
    image_url: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&auto=format&fit=crop",
    category: "AI & Automation",
    tags: ["Generative AI", "Transformation"],
    source: "Harvard Business Review",
    author: "Andrew McAfee",
    ai_tags: ["Operating Model", "Enterprise AI", "Change Management"],
    is_featured: true,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 142,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000002",
    title: "From Cost Center to Value Driver: Reimagining Finance in the Age of AI",
    summary: "How AI-powered automation is reshaping the finance function from transaction processing to strategic advisory.",
    ai_summary: "Finance organizations embracing AI automation for transactional work are freeing capacity to become true strategic partners. This piece outlines the CFO roadmap from cost center to value driver — with practical steps and real-world examples from global enterprises.",
    content: `For decades, finance has been defined by its role as the keeper of the books. That definition is changing — fast.

AI-powered automation is handling the reconciliations, the close processes, the variance analyses. What's left for finance professionals is the work that actually requires judgment: scenario modeling, capital allocation, strategic partnering with the business.

The CFOs leading this transition share a common playbook. They start by automating the highest-volume, lowest-judgment work first — invoice processing, account reconciliation, regulatory reporting. This creates immediate ROI and builds organizational confidence in AI.

Then they reinvest the liberated capacity into FP&A, business partnering, and M&A support. Finance teams that once spent 80% of their time on transaction processing now spend 60% on analysis and advice.

The transformation isn't painless. It requires reskilling, new tooling, and — most critically — a shift in identity. Finance leaders must help their teams see themselves as analysts and advisors, not accountants.`,
    url: "https://mckinsey.com/finance-ai-value",
    image_url: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop",
    category: "Finance",
    tags: ["CFO", "Finance Transformation"],
    source: "McKinsey & Company",
    author: "Mihir Desai",
    ai_tags: ["Automation", "Strategic Finance", "AI"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 87,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000003",
    title: "Leading Through Ambiguity: The New Leadership Playbook for 2026",
    summary: "What distinguishes the most effective leaders in periods of rapid technological and geopolitical change.",
    ai_summary: "The leaders who thrive today share three traits: comfort with incomplete information, ability to mobilize coalitions quickly, and a bias toward learning over certainty. This article breaks down the new leadership playbook with case studies from global enterprises navigating AI disruption.",
    content: `The old leadership playbook — set a clear vision, build a detailed plan, execute consistently — was built for a more predictable world. That world is gone.

Today's most effective leaders have learned to lead in fog. They make decisions with 60% of the information they'd like, adjust course faster than their organizations are comfortable with, and create psychological safety for their teams to do the same.

Research across 200 global executives in the past 18 months reveals three distinguishing behaviors. First, they separate reversible from irreversible decisions — moving fast on the former, slow and deliberate on the latter. Second, they invest heavily in sensing networks: diverse information sources, dissenting voices, and front-line feedback loops. Third, they are explicit about uncertainty with their teams rather than projecting false confidence.

For leaders in AI-intensive industries, there's an additional skill: knowing when to trust the model and when to override it. The best leaders are developing sophisticated intuition about AI's blind spots — and building organizations that can course-correct when AI gets it wrong.`,
    url: "https://strategy-business.com/leadership-2026",
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop",
    category: "Leadership",
    tags: ["Leadership", "Change Management"],
    source: "Strategy+Business",
    author: "Roger Martin",
    ai_tags: ["Executive", "Ambiguity", "Decision-Making"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 64,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000004",
    title: "Agentic AI in Enterprise Operations: Moving from Demo to Deployment",
    summary: "The gap between AI agent demonstrations and production deployments — and how to close it.",
    ai_summary: "Most enterprise AI agent projects stall between proof-of-concept and production. This article identifies the five most common deployment blockers — data access, security, change management, governance, and integration — and provides a practical framework for overcoming each one.",
    content: `Every enterprise has seen the demo. The AI agent seamlessly navigates a complex workflow, makes smart decisions, hands off to humans at exactly the right moment. The audience is impressed. The pilot is approved.

Six months later, the project is stuck. Sound familiar?

The gap between AI agent demos and production deployment is the defining challenge of enterprise AI right now. After analyzing 40 enterprise agentic AI deployments across industries, five blockers emerge with remarkable consistency.

Data access is the first and most common. Agents need clean, real-time data to act — and most enterprises' data infrastructure wasn't built for that. The fix is often less about AI and more about data engineering.

Security and compliance is the second blocker. Agents that can take actions on behalf of users raise new questions about authorization, audit trails, and liability. Companies that solve this build dedicated "agent security" frameworks before scaling.

The other three blockers — change management, governance, and integration complexity — are equally important but more solvable with the right organizational scaffolding.

The enterprises that have successfully scaled agentic AI share one trait: they treated deployment as a product discipline, not an IT project.`,
    url: "https://gartner.com/agentic-ai-deployment",
    image_url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&auto=format&fit=crop",
    category: "AI & Automation",
    tags: ["Agentic AI", "Deployment"],
    source: "Gartner Research",
    author: "Erick Brethenoux",
    ai_tags: ["Enterprise AI", "Operations", "Governance"],
    is_featured: true,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 201,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000005",
    title: "Building High-Performance Distributed Teams: Lessons from Global Operations Leaders",
    summary: "Research-backed practices for leading geographically distributed teams to peak performance.",
    ai_summary: "Organizations with globally distributed workforces outperform on delivery when they invest in structured async communication, trust-building rituals, and deliberate career development at a distance. A study of 200 global teams reveals what actually separates high performers from the rest.",
    content: `Managing a distributed team across time zones, cultures, and languages is one of the hardest things a leader can do well. Most don't.

The research is clear: distributed teams underperform co-located teams on coordination and trust — but outperform them on diversity of thought, resilience, and access to talent. The question isn't whether to build distributed teams, but how to unlock their upside while minimizing the coordination costs.

Three practices consistently distinguish high-performing distributed teams. First, they treat asynchronous communication as a first-class discipline. Written updates, recorded context, and documented decisions aren't bureaucracy — they're the connective tissue that replaces hallway conversations.

Second, they invest disproportionately in in-person moments. Counter-intuitively, the highest-performing distributed teams meet face-to-face more often than average — but they're intentional about when and why. Team launches, major pivots, and culture-building moments are worth the travel budget.

Third, they build career development infrastructure that works at a distance. Sponsorship, visibility, and growth conversations don't happen organically on distributed teams — they must be designed in.

For Genpact, where delivery teams span Hyderabad, Warsaw, and Guadalajara, these lessons are directly applicable.`,
    url: "https://deloitte.com/distributed-teams",
    image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop",
    category: "People & Culture",
    tags: ["Remote Work", "Team Performance"],
    source: "Deloitte Insights",
    author: "Erica Volini",
    ai_tags: ["Culture", "Distributed Teams", "Leadership"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 53,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── Steve's YouTube picks (continued) ───────────────────────────────────
  {
    id: "demo-art-vid-0000-0000-000000000002",
    title: "Andrej Karpathy: Recent Work and What's Next in AI",
    summary: "Karpathy's wide-ranging talk at Sequoia AI Ascent covers his latest thinking on AI development, model capabilities, and what the next wave of progress looks like from the perspective of one of the field's most respected researchers.",
    ai_summary: "Andrej Karpathy synthesizes his recent research and observations on the current state of AI development at Sequoia's AI Ascent conference. Covering everything from model architecture intuitions to the evolving role of human oversight, this talk is essential viewing for anyone tracking where the frontier is moving.",
    content: null,
    url: "https://youtu.be/96jN2OCOfLs",
    image_url: "https://img.youtube.com/vi/96jN2OCOfLs/maxresdefault.jpg",
    category: "AI & Automation",
    tags: ["AI Research", "LLMs", "Foundation Models"],
    source: "Sequoia AI Ascent 2025",
    author: "Andrej Karpathy",
    ai_tags: ["AI Research", "Model Capabilities", "Future of AI"],
    is_featured: false,
    status: "published" as const,
    content_type: "video" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-vid-0000-0000-000000000003",
    title: "Building with Claude: Essential Tips for Non-Technical Builders",
    summary: "The PM behind Claude Code gets interviewed on what non-technical people need to know to build powerful AI applications — packed with practical tips for anyone in operations, finance, or consulting who wants to build without writing code.",
    ai_summary: "In this in-depth podcast interview, the Claude Code PM breaks down what non-technical builders need to succeed with AI — from prompt engineering principles to knowing when to bring in engineering support. If you're in a non-technical role and want to build AI-powered tools, this episode is a practical roadmap.",
    content: null,
    url: "https://youtu.be/PplmzlgE0kg",
    image_url: "https://img.youtube.com/vi/PplmzlgE0kg/maxresdefault.jpg",
    category: "Technology",
    tags: ["No-Code", "AI Tools", "Product Management"],
    source: "Podcast · Sequoia AI Ascent 2025",
    author: "Anthropic PM",
    ai_tags: ["Non-Technical Builders", "AI Adoption", "Claude"],
    is_featured: false,
    status: "published" as const,
    content_type: "video" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-vid-0000-0000-000000000004",
    title: "How to Build an AI-Native Company",
    summary: "A concise, instructive guide to what it actually means to rotate a company toward AI — not just adding AI tools, but restructuring how teams work, decide, and create. Highly relevant as Genpact accelerates its own AI transformation.",
    ai_summary: "This sharp video cuts through the noise on what 'AI-native' actually means in practice. Beyond deploying AI tools, truly AI-native companies redesign their operating models, decision loops, and talent strategies around AI capabilities from the ground up. The lessons here are directly applicable to Genpact's transformation journey.",
    content: null,
    url: "https://youtu.be/EN7frwQIbKc",
    image_url: "https://img.youtube.com/vi/EN7frwQIbKc/maxresdefault.jpg",
    category: "Strategy",
    tags: ["AI Transformation", "Operating Model", "AI-Native"],
    source: "YouTube",
    author: null,
    ai_tags: ["Digital Transformation", "Company Building", "AI Strategy"],
    is_featured: false,
    status: "published" as const,
    content_type: "video" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-vid-0000-0000-000000000005",
    title: "GPT-o3 and What AI's New Math Abilities Mean for Knowledge Work",
    summary: "The latest frontier models are achieving near-perfect scores on competition mathematics. This video explains what that capability jump actually means — for research, consulting, finance, and any knowledge work that relies on quantitative reasoning.",
    ai_summary: "Advanced reasoning in the latest AI models represents a qualitative shift in what AI can do in quantitative domains. This video explores how AI's growing mathematical capabilities are set to transform financial modeling, scientific research, and strategic analysis — and what it means for professionals whose edge has historically come from analytical skill.",
    content: null,
    url: "https://youtu.be/9-TVwv6wtGQ",
    image_url: "https://img.youtube.com/vi/9-TVwv6wtGQ/maxresdefault.jpg",
    category: "AI & Automation",
    tags: ["AI Reasoning", "Mathematical AI", "Knowledge Work"],
    source: "YouTube",
    author: null,
    ai_tags: ["AI Capabilities", "Quantitative Reasoning", "Future of Work"],
    is_featured: false,
    status: "published" as const,
    content_type: "video" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── Anthropic ────────────────────────────────────────────────────────────
  {
    id: "demo-art-0000-0000-0000-000000000006",
    title: "Claude's Character: How Anthropic Thinks About AI Personality and Values",
    summary: "Anthropic's deep dive into how and why Claude has a consistent character — curiosity, honesty, care — and why they believe values-aligned AI is the key to building systems that are genuinely useful at scale.",
    ai_summary: "Anthropic explains the philosophy behind Claude's character: that an AI with genuine values, curiosity, and intellectual honesty is more useful and safer than one that merely follows rules. This piece is essential reading for anyone deploying AI in client-facing or high-stakes enterprise contexts where trust is paramount.",
    content: null,
    url: "https://www.anthropic.com/news/claudes-character",
    image_url: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop",
    category: "AI & Automation",
    tags: ["Claude", "AI Safety", "Values"],
    source: "Anthropic",
    author: "Anthropic",
    ai_tags: ["AI Alignment", "Responsible AI", "Enterprise AI"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000007",
    title: "Anthropic's Responsible Scaling Policy: A Framework for Safe AI Development",
    summary: "How Anthropic structures its approach to deploying increasingly powerful models — with built-in safety evaluations, capability thresholds, and commitments to pause deployment if certain risk criteria are met.",
    ai_summary: "Anthropic's Responsible Scaling Policy (RSP) establishes concrete safety commitments tied to model capability levels — a framework increasingly relevant for enterprise clients who need to understand the governance behind the AI they're deploying. Understanding the RSP helps leaders make informed decisions about AI risk tolerance.",
    content: null,
    url: "https://www.anthropic.com/responsible-scaling-policy",
    image_url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&auto=format&fit=crop",
    category: "AI & Automation",
    tags: ["AI Safety", "Governance", "Responsible AI"],
    source: "Anthropic",
    author: "Anthropic",
    ai_tags: ["AI Policy", "Enterprise Governance", "Risk Management"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── McKinsey ─────────────────────────────────────────────────────────────
  {
    id: "demo-art-0000-0000-0000-000000000008",
    title: "Superagency in the Workplace: Empowering People to Unlock AI's Full Potential",
    summary: "McKinsey's landmark 2025 report finds that companies where employees have genuine agency over how they use AI outperform peers on productivity, satisfaction, and innovation — by a significant margin.",
    ai_summary: "McKinsey's research reveals a counterintuitive finding: the companies getting the most from AI are the ones giving employees more autonomy in how they use it, not less. 'Superagency' — the combination of AI capability and human judgment — is the new competitive advantage. The report includes a practical framework for enabling it at scale.",
    content: null,
    url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/superagency-in-the-workplace",
    image_url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&auto=format&fit=crop",
    category: "People & Culture",
    tags: ["Future of Work", "AI Adoption", "Employee Empowerment"],
    source: "McKinsey & Company",
    author: "McKinsey Global Institute",
    ai_tags: ["Workforce Transformation", "AI Agency", "Productivity"],
    is_featured: true,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000009",
    title: "The Economic Potential of Generative AI: The Next Productivity Frontier",
    summary: "McKinsey's definitive analysis of generative AI's economic impact estimates $2.6–4.4 trillion in annual value across industries — with the largest gains in knowledge work, customer operations, and software development.",
    ai_summary: "This foundational McKinsey report quantifies generative AI's potential across 63 use cases in 16 business functions. For Genpact's focus areas — finance, operations, and technology services — the research provides the evidence base for where to prioritize AI investment and how to size the opportunity for clients.",
    content: null,
    url: "https://www.mckinsey.com/capabilities/mckinsey-digital/our-insights/the-economic-potential-of-generative-ai",
    image_url: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop",
    category: "Strategy",
    tags: ["Generative AI", "Economic Impact", "Productivity"],
    source: "McKinsey Global Institute",
    author: "McKinsey Global Institute",
    ai_tags: ["AI Economics", "Business Value", "Enterprise Strategy"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── Deloitte ─────────────────────────────────────────────────────────────
  {
    id: "demo-art-0000-0000-0000-000000000010",
    title: "State of Generative AI in the Enterprise: Q1 2025",
    summary: "Deloitte's quarterly enterprise AI survey tracks adoption, ROI realization, and the barriers that are slowing scale. The latest edition shows a growing gap between AI leaders and laggards — and identifies the organizational factors that separate them.",
    ai_summary: "Deloitte's enterprise AI survey data reveals that just 26% of organizations report meaningful ROI from generative AI pilots — but that number jumps to 74% among companies with dedicated AI governance structures. The implication for Genpact and its clients: governance and change management are more important than the technology itself.",
    content: null,
    url: "https://www2.deloitte.com/us/en/pages/consulting/articles/state-of-generative-ai-in-the-enterprise.html",
    image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop",
    category: "AI & Automation",
    tags: ["Enterprise AI", "ROI", "AI Adoption"],
    source: "Deloitte Insights",
    author: "Deloitte AI Institute",
    ai_tags: ["AI Governance", "Digital Transformation", "Enterprise Strategy"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000011",
    title: "The Finance Function of the Future: AI-Augmented and Human-Led",
    summary: "Deloitte maps the transformation of finance from scorekeeper to strategic advisor — with AI handling 70%+ of transactional work and freeing CFOs to focus on capital allocation, scenario planning, and enterprise risk.",
    ai_summary: "Deloitte's research on the future of finance describes a function fundamentally reshaped by AI: routine work automated, judgment work elevated. For Genpact's finance transformation practice, this report provides the reference architecture for the conversations clients are having about what their finance organizations should look like in 2027 and beyond.",
    content: null,
    url: "https://www2.deloitte.com/us/en/insights/topics/strategy/finance-function-of-the-future.html",
    image_url: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop",
    category: "Finance",
    tags: ["Finance Transformation", "CFO", "AI Augmentation"],
    source: "Deloitte Insights",
    author: "Deloitte CFO Program",
    ai_tags: ["Finance Operations", "Automation", "Strategic Finance"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },

  // ── BCG ──────────────────────────────────────────────────────────────────
  {
    id: "demo-art-0000-0000-0000-000000000012",
    title: "From Potential to Profit with GenAI: Moving Past the Pilot Trap",
    summary: "BCG's research on why 75% of GenAI pilots fail to scale — and the specific organizational design, data infrastructure, and change management interventions that separate companies achieving profit from those stuck in experimentation.",
    ai_summary: "BCG identifies the 'pilot trap' as the defining challenge in enterprise AI: organizations running dozens of proof-of-concepts but scaling none. The fix isn't better technology — it's better operating model design. This report provides the diagnostic framework and intervention playbook that Genpact can use with clients at this stage.",
    content: null,
    url: "https://www.bcg.com/publications/2024/from-potential-to-profit-with-genai",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop",
    category: "Strategy",
    tags: ["GenAI", "Scaling AI", "Operating Model"],
    source: "Boston Consulting Group",
    author: "BCG Henderson Institute",
    ai_tags: ["AI Scale", "Change Management", "Enterprise Transformation"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-art-0000-0000-0000-000000000013",
    title: "AI at Work: BCG's 2025 People + Technology Report",
    summary: "BCG's annual survey of 13,000 employees and executives across 20 countries reveals the widening gap between AI enthusiasm and AI readiness — and identifies the five practices of companies that are closing it fastest.",
    ai_summary: "BCG's global workforce research finds that while 87% of executives believe AI will be transformative, only 19% of employees say they have the skills and tools to use it effectively today. The five practices of AI-ready organizations — including role-based upskilling, visible leadership commitment, and psychological safety around AI experimentation — are directly actionable for Genpact's people transformation work.",
    content: null,
    url: "https://www.bcg.com/publications/2025/ai-at-work-people-technology-report",
    image_url: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&auto=format&fit=crop",
    category: "People & Culture",
    tags: ["AI Readiness", "Workforce", "Upskilling"],
    source: "Boston Consulting Group",
    author: "BCG",
    ai_tags: ["Talent Development", "AI Adoption", "Change Management"],
    is_featured: false,
    status: "published" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_PENDING_ARTICLES: Article[] = [
  {
    id: "demo-pending-0000-0000-0000-000000000001",
    title: "The Talent Equation: Why AI Skills Are Now the Most Valuable Currency in Enterprise Hiring",
    summary: "New research reveals the premium companies are paying for AI-literate talent across every function.",
    ai_summary: "Organizations are paying 20-35% salary premiums for employees who can work effectively alongside AI systems. This piece examines what AI literacy actually means in practice across finance, operations, and technology roles, and how companies are building it internally.",
    content: null,
    url: "https://weforum.org/ai-talent-premium-2026",
    image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&auto=format&fit=crop",
    category: "People & Culture",
    tags: ["Talent", "AI Skills", "Future of Work"],
    source: "World Economic Forum",
    author: "Saadia Zahidi",
    ai_tags: ["Hiring", "AI Literacy", "Compensation"],
    is_featured: false,
    status: "pending" as const,
    content_type: "article" as const,
    suggested_by_ai: false,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-pending-0000-0000-0000-000000000002",
    title: "Process Intelligence: The Missing Layer in Enterprise AI Deployments",
    summary: "Why AI initiatives fail without first mapping and optimizing the processes they're meant to transform.",
    ai_summary: "Process intelligence — the discipline of understanding how work actually flows before automating it — is emerging as the critical missing ingredient in most AI deployments. Companies that invest in process mining before AI see 3x higher ROI on automation projects.",
    content: null,
    url: "https://forrester.com/process-intelligence-ai",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop",
    category: "Operations",
    tags: ["Process Mining", "Automation", "Operations"],
    source: "Forrester Research",
    author: "Craig Le Clair",
    ai_tags: ["Process Intelligence", "Automation ROI", "Digital Operations"],
    is_featured: false,
    status: "pending" as const,
    content_type: "article" as const,
    suggested_by_ai: true,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: "demo-pending-0000-0000-0000-000000000003",
    title: "Data Governance in the Age of Generative AI: A Practical Framework",
    summary: "As GenAI proliferates across the enterprise, data governance is no longer optional — it's existential.",
    ai_summary: "Enterprises deploying generative AI without robust data governance frameworks are accumulating hidden risk. This practical guide outlines the five pillars of AI-ready data governance and how leading organizations are implementing them without slowing innovation.",
    content: null,
    url: "https://gartner.com/data-governance-genai",
    image_url: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop",
    category: "Data & Analytics",
    tags: ["Data Governance", "GenAI", "Compliance"],
    source: "Gartner",
    author: "Alan D. Duncan",
    ai_tags: ["Data Quality", "AI Risk", "Governance"],
    is_featured: false,
    status: "pending" as const,
    content_type: "article" as const,
    suggested_by_ai: true,
    read_count: 0,
    created_by: DEMO_USER_ID,
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
  },
];

export const DEMO_AI_SUGGESTIONS: ArticleSuggestion[] = [
  {
    id: "sug-001",
    title: "How CFOs Are Using AI Agents to Close the Books in Hours, Not Days",
    source: "CFO Magazine",
    category: "Finance",
    summary: "AI-powered financial close automation is cutting month-end close cycles from weeks to hours at leading enterprises. Explores the technology stack, change management approach, and measurable outcomes.",
    search_hint: "AI agents financial close automation CFO 2025 2026",
  },
  {
    id: "sug-002",
    title: "The Responsible AI Playbook: How Global Companies Are Building Ethical AI Programs",
    source: "MIT Sloan Management Review",
    category: "AI & Automation",
    summary: "As AI capabilities expand, governance and ethics programs are becoming competitive differentiators. This piece outlines the frameworks that leading multinationals are using to ensure AI is deployed responsibly.",
    search_hint: "responsible AI governance program enterprise ethics MIT Sloan",
  },
  {
    id: "sug-003",
    title: "Supply Chain Resilience in 2026: The Role of Predictive AI",
    source: "McKinsey & Company",
    category: "Operations",
    summary: "Predictive AI is transforming supply chain risk management from reactive to proactive. Companies using AI-powered demand forecasting are reducing inventory costs 20-30% while improving service levels.",
    search_hint: "supply chain AI predictive analytics resilience McKinsey 2026",
  },
  {
    id: "sug-004",
    title: "Why the Best Leaders Are Becoming 'AI Translators' for Their Organizations",
    source: "Harvard Business Review",
    category: "Leadership",
    summary: "The highest-value leadership skill emerging in 2026 is the ability to bridge AI capability and business application — translating technical possibilities into strategic decisions that non-technical stakeholders can act on.",
    search_hint: "AI leadership translator business HBR executive 2026",
  },
  {
    id: "sug-005",
    title: "The New ROI of Learning: How L&D Is Proving Its Value in the AI Era",
    source: "Deloitte Insights",
    category: "People & Culture",
    summary: "Learning & development programs are under pressure to demonstrate measurable business impact. New frameworks connect skill development directly to productivity gains, retention, and AI adoption velocity.",
    search_hint: "L&D ROI AI era learning development Deloitte 2026",
  },
  {
    id: "sug-006",
    title: "Cloud FinOps at Scale: Taming the Cost of Enterprise AI Infrastructure",
    source: "Forrester Research",
    category: "Technology",
    summary: "AI workloads are driving unexpected cloud cost explosions at enterprises. FinOps practices — combining finance, engineering, and operations — are emerging as the discipline that keeps AI investments profitable.",
    search_hint: "cloud FinOps AI infrastructure cost management enterprise Forrester",
  },
];

export const DEMO_BREW: MorningBrew = {
  id: "demo-brew-0000-0000-0000-000000000001",
  brew_date: new Date().toISOString().split("T")[0],
  article_ids: [
    "demo-art-0000-0000-0000-000000000001",
    "demo-art-0000-0000-0000-000000000004",
    "demo-art-0000-0000-0000-000000000002",
  ],
  ai_intro: "Good morning! Today's brew explores the forces reshaping enterprise work: AI that moves from pilot to production, finance teams reinventing their purpose, and the transformational leap to becoming an AI-first organization. Three perspectives, one clear message — the window for bold action is now.",
  theme: "From Pilot to Production",
  created_at: new Date().toISOString(),
  articles: [
    DEMO_ARTICLES[0],
    DEMO_ARTICLES[3],
    DEMO_ARTICLES[1],
  ],
};
